language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-22
  - android-26
  - sys-img-armeabi-v7a-android-22
  - extra-android-m2repository

script: ./travis-build.sh

deploy:
- provider: releases
  api_key:
    secure: q6I0xWE2b0VgodltxT1/Lp2lSsCUDehzcfIV/qMa61aWPogW/Dz6RWP3Wy3tyYH60tQPaaLMZGGzoJdhGbyOcjez3XviSqOC0z+TEgyhhiWyyhds4/YEY3Bny37Kj0UNdnYEidLOCfPgRA6UMynfGUGFBIoIVN3N2Pb8/mz+L9+b5oePU92JUL8HcofrvQetvZ+vubNuil+1TdJ08qlUd7mGpKsEQ0MXWbO5rpD2PBgIkYM2hZiwTERvHWDO8XNdFMwmuWLZqF0AslTglGjfaJLeLsS22AwFzpPCJ8Geb1ocgm9INFe5Ch8nb0FzHEpZq7zBtcSsCR3VmN0NqixgqopgCs3153Ty8jMLPMraW8sAmSmD6X7QKAFqpIS+qX3ylpkcopOIWOsEGmpV4zbZURJiDF8LxBpzg9Tb5wd4wpL8PmIkrXWbqjwoS/EgD/mATss9WJsu09pIZ7KaqsX0pL3J3LgsE9sE6ZrdGHDHPYI9iZIa8A7y866UUQ1kjw4eT/LpUpqq2ACZjq59zl9UaM3310KyxoF9S5gojFKYtbzZHLWlMxmarkczLj1wlpYADUEqgCLJhq0P4FaMRUv57Esprhd1CfqBYCJN75hFlD1ZGUGTpA9CjkR9YF4M3j5ULph13zmY7/HxSPfvvh1MTkT0E3bWU0aInc3DtwADMAA=
  file: TrollsGames-${TRAVIS_TAG}.apk
  skip_cleanup: true
  on:
    repo: massix/TrollsGamesApp
    tags: true

- provider: script
  skip_cleanup: true
  script: scp TrollsGames-${TRAVIS_TAG}.apk prod:trolls-apk/prod/
  skip_cleanup: true
  on:
    tags: true
    branch: master

- provider: script
  skip_cleanup: true
  script: scp TrollsGames.apk prod:trolls-apk/staging/
  on:
    branch: develop

- provider: script
  skip_cleanup: true
  script: scp TrollsGames.apk prod:trolls-apk/debug/
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^feature/.*$"

before_install:
- openssl aes-256-cbc -K $encrypted_cbbd4fbdf86e_key -iv $encrypted_cbbd4fbdf86e_iv
  -in secrets.tgz.enc -out secrets.tgz -d
- tar xzf secrets.tgz
- cp ssh-config $HOME/.ssh/config
- cp travis-key $HOME/.ssh/
- cp $TRAVIS_BUILD_DIR/.keystore $HOME

env:
  global:
    secure: IQOmd9YVQPAgcQJSzw3J0NPnA09aid3E9NRRE2mvNNhDi823kRSvGWrk3BgQdRzhd436haUE0q/JTfL+3skmayaHSNkjNWc5VLz8pXY4uiJiuLOQ7WiF+dkD1WNNK1nNhcfJ3kttSybXzEDFw6CESCFIELDzDNZeJseF3fS64HApm1FOZeSouBSGK7T1vvgiB2zgjfvfT9lGzpOKqYxiQ+YFb8us/tyWTR1Vsv6PutljWA4y903GXyCgk/WNoqMJsZvWlE555vFDK80wvjFhNhoHlYbD+PgicjVeASzuNn0a6nGB6APeSKXxeWUa2kzCNhMMzT9992ZVsrpUKrzwMuW2jqAUkpY50RyqjQ6G7bTMd4qRkeumDP4BxxTM1BakleJJrafOMXlLfBxNwwgpBP3s+ORYBjoahi+u/Tdkpwc8zbHXcOnQWg5PQxe+AkjibyQHV13JYL9cKHY4trNOYR41gpCFOhvOcCc0uECwMQKjaJEFtaJTTzB9fUb52iW64MGaCb/uVltCJK0qKza/XbAyXFa8cxFhrY94G4Z8+scwn8NSGHZRlgohsniWOyKdnUZnDEsOoXdxel4Z9EUFAWNmMiLYOnc4EO87nE7ByHVX4phGpQfVXaIUl+pD6y2bB+AIW/9wWil65J91+XkUTkCKMBcRlK/VxqeB8OVVwsw=
