language: android
jdk: oraclejdk8
sudo: false

android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-22
  - android-26
  - sys-img-armeabi-v7a-android-22
  - extra-android-m2repository

script: ./gradlew build check

deploy:
  provider: releases
  api_key:
    secure: q6I0xWE2b0VgodltxT1/Lp2lSsCUDehzcfIV/qMa61aWPogW/Dz6RWP3Wy3tyYH60tQPaaLMZGGzoJdhGbyOcjez3XviSqOC0z+TEgyhhiWyyhds4/YEY3Bny37Kj0UNdnYEidLOCfPgRA6UMynfGUGFBIoIVN3N2Pb8/mz+L9+b5oePU92JUL8HcofrvQetvZ+vubNuil+1TdJ08qlUd7mGpKsEQ0MXWbO5rpD2PBgIkYM2hZiwTERvHWDO8XNdFMwmuWLZqF0AslTglGjfaJLeLsS22AwFzpPCJ8Geb1ocgm9INFe5Ch8nb0FzHEpZq7zBtcSsCR3VmN0NqixgqopgCs3153Ty8jMLPMraW8sAmSmD6X7QKAFqpIS+qX3ylpkcopOIWOsEGmpV4zbZURJiDF8LxBpzg9Tb5wd4wpL8PmIkrXWbqjwoS/EgD/mATss9WJsu09pIZ7KaqsX0pL3J3LgsE9sE6ZrdGHDHPYI9iZIa8A7y866UUQ1kjw4eT/LpUpqq2ACZjq59zl9UaM3310KyxoF9S5gojFKYtbzZHLWlMxmarkczLj1wlpYADUEqgCLJhq0P4FaMRUv57Esprhd1CfqBYCJN75hFlD1ZGUGTpA9CjkR9YF4M3j5ULph13zmY7/HxSPfvvh1MTkT0E3bWU0aInc3DtwADMAA=
  file: app/build/outputs/apk/app-release-unsigned.apk
  skip_cleanup: true
  on:
    repo: massix/TrollsGamesApp
    tags: true
